
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 19 02:24:04 CST 2020
//----------------------------------------------------

package Practica.Analisis.SQL;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 15;
  public static final int CADENA = 18;
  public static final int INSERTAR = 5;
  public static final int OR = 16;
  public static final int FINLINEA = 14;
  public static final int ELIMINAR = 10;
  public static final int ID = 19;
  public static final int NUM = 20;
  public static final int FILTRAR = 4;
  public static final int VALORES = 6;
  public static final int ASIGNAR = 8;
  public static final int ACTUALIZAR = 7;
  public static final int COMA = 13;
  public static final int ASIGNACION = 9;
  public static final int EOF = 0;
  public static final int OPERADOR = 21;
  public static final int TODO = 17;
  public static final int error = 1;
  public static final int EN = 3;
  public static final int PARENTESISC = 12;
  public static final int PATH = 22;
  public static final int PARENTESISA = 11;
  public static final int SELECCIONAR = 2;
}

