
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 12 10:03:11 CST 2020
//----------------------------------------------------

package Practica.Analisis.IDE;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 13;
  public static final int FINPROYECTO = 3;
  public static final int SLASH = 15;
  public static final int CARPETA = 4;
  public static final int ARCHIVO = 6;
  public static final int MENOR = 7;
  public static final int PROYECTO = 2;
  public static final int ubicacion = 12;
  public static final int EOF = 0;
  public static final int MAYOR = 8;
  public static final int FINCARPETA = 5;
  public static final int ASIGNACION = 10;
  public static final int error = 1;
  public static final int PATH = 14;
  public static final int nombre = 11;
  public static final int COMILLA = 9;
}

