
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 18 03:59:31 CST 2020
//----------------------------------------------------

package Practica.Analisis.CSV;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 5;
  public static final int COMA = 2;
  public static final int FINLINEA = 3;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final int CADENA = 4;
}

