/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica.Gui;

import Practica.Analisis.IDE.LexerIDE;
import Practica.Analisis.IDE.ParserIDE;
import Practica.Objetos.Token;
import Practica.Utilidades.ReaderFiles;
import Practica.Utilidades.TreeManager;
import java.awt.Color;
import java.io.File;
import java.io.StringReader;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author fxhnd
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }
    
    public void showError(LexerIDE lexer){
        String text = "";
        for (Token error : lexer.getErrores()) {
            text+="Error: "+error.getLexem()+" en la linea: "+error.getLine()+" y la columna: "+error.getColumn()+"\n";
        }
        TextDialog.setForeground(Color.red);
        TextDialog.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoErrores = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextDialog = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AbrirProyectoButton = new javax.swing.JMenuItem();
        GuardarProyectoButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CrearArchivoButton = new javax.swing.JMenuItem();
        EliminarArchivoButton = new javax.swing.JMenuItem();
        EditarNombreButton = new javax.swing.JMenu();

        DialogoErrores.setSize(new java.awt.Dimension(800, 300));

        TextDialog.setColumns(20);
        TextDialog.setRows(5);
        jScrollPane3.setViewportView(TextDialog);

        javax.swing.GroupLayout DialogoErroresLayout = new javax.swing.GroupLayout(DialogoErrores.getContentPane());
        DialogoErrores.getContentPane().setLayout(DialogoErroresLayout);
        DialogoErroresLayout.setHorizontalGroup(
            DialogoErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        DialogoErroresLayout.setVerticalGroup(
            DialogoErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("<Sin Proyecto>");
        Tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        Tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tree);

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane2.setViewportView(Text);

        jLabel1.setText("Orden SQL");

        jLabel2.setText("Documento Abierto");

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Proyecto");

        AbrirProyectoButton.setText("Abrir");
        AbrirProyectoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirProyectoButtonActionPerformed(evt);
            }
        });
        jMenu1.add(AbrirProyectoButton);

        GuardarProyectoButton.setText("Guardar");
        GuardarProyectoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProyectoButtonActionPerformed(evt);
            }
        });
        jMenu1.add(GuardarProyectoButton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Archivo");

        CrearArchivoButton.setText("Crear");
        CrearArchivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearArchivoButtonActionPerformed(evt);
            }
        });
        jMenu2.add(CrearArchivoButton);

        EliminarArchivoButton.setText("Eliminar");
        EliminarArchivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarArchivoButtonActionPerformed(evt);
            }
        });
        jMenu2.add(EliminarArchivoButton);

        jMenuBar1.add(jMenu2);

        EditarNombreButton.setText("Cambiar Nombre");
        EditarNombreButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarNombreButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(EditarNombreButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreeMouseClicked
        
    }//GEN-LAST:event_TreeMouseClicked

    private void AbrirProyectoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirProyectoButtonActionPerformed
        this.Text.setText(InterfaceManager.openProyect());
    }//GEN-LAST:event_AbrirProyectoButtonActionPerformed

    private void GuardarProyectoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProyectoButtonActionPerformed
        InterfaceManager.saveProyect(this.Text.getText());
    }//GEN-LAST:event_GuardarProyectoButtonActionPerformed

    private void CrearArchivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearArchivoButtonActionPerformed
        if(Tree.getSelectionPath()!=null){    
            String nombre = JOptionPane.showInputDialog("Ingrese el nombre del documento.");
            if(nombre != null){
                if(!nombre.isEmpty()){
                    Tree.setModel(TreeManager.addChild(nombre, Tree));
                }else{
                    JOptionPane.showMessageDialog(null, "Ingrese un nombre valido.","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Primero seleccione la ubicacion en la que desea crear el archivo","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CrearArchivoButtonActionPerformed

    private void EliminarArchivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarArchivoButtonActionPerformed
        if(Tree.getSelectionPath()!=null){    
            Tree.setModel(TreeManager.removeChild(Tree));
        }else{
            JOptionPane.showMessageDialog(null, "Primero seleccione el archivo que desea eliminar","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EliminarArchivoButtonActionPerformed

    private void EditarNombreButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarNombreButtonMouseClicked
        if(Tree.getSelectionPath()!=null){    
            String nombre = JOptionPane.showInputDialog("Ingrese el nombre nuevo.");
            if(nombre != null){
                if(!nombre.isEmpty()){
                    Tree.setModel(TreeManager.setNodeName(nombre, Tree));
                }else{
                    JOptionPane.showMessageDialog(null, "Ingrese un nombre valido.","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Primero seleccione el archivo/carpeta/proyecto al que desea cambiar el nombre.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditarNombreButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String texto = this.Text.getText();
        LexerIDE lexer = new LexerIDE(new StringReader(texto));
        Tree.setModel(TreeManager.createJTree(lexer));
        try {
            if(lexer.getErrores().isEmpty()){
                new ParserIDE(lexer).parse();
            }else{
                showError(lexer);
            }
        } catch (Exception ex) {
            System.out.println("error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirProyectoButton;
    private javax.swing.JMenuItem CrearArchivoButton;
    private javax.swing.JDialog DialogoErrores;
    private javax.swing.JMenu EditarNombreButton;
    private javax.swing.JMenuItem EliminarArchivoButton;
    private javax.swing.JMenuItem GuardarProyectoButton;
    private javax.swing.JTextArea Text;
    private javax.swing.JTextArea TextDialog;
    private javax.swing.JTree Tree;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
